llvm-project-source: Drop staging clang 13 patches for intel
Clang 14 seems to have this problem resolved, so this patch is no more needed,
I assume aligned branch will be used:
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/tree/llvm_release_140

Observed issue on seco b68 was:

    llvm-project-source-14.0.1-r0\
    /git/llvm/projects/llvm-spirv/lib/SPIRV/libSPIRV/SPIRVOpCode.h:44:10: \
    fatal error: spirv/unified1/spirv.hpp: No such file or directory

Relate-to: https://booting.oniroproject.org/rzr/meta-oniro-blueprint-flutter/-/issues/3
Relate-to: https://booting.oniroproject.org/distro/meta-seco-intel/-/issues/9
Relate-to: https://gitlab.eclipse.org/eclipse/oniro-core/oniro/-/issues/361
Cc: Bernhard Rosenkraenzer <bernhard.rosenkraenzer.ext@huawei.com>
Signed-off-by: Philippe Coval <philippe.coval.ext@huawei.com>